# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6471f542e1244f253a1a3e3910fdecc33327b5fca3fc959adab06667b2e928a7b4291ce01ce0cb7ad5d271d2c2b01eba3949e273aa5dd5c40e8f2ad195f4eb48

test:
  secret_key_base: 90a36e76c06ff9f00fad9b68bfe993f92169416bebb3671474449a41d1272889bc52bc23978a2f219cc0ad9cc15b5bc2e417ec52d7988d52793dfdd0f24cf42d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
